function ntt2mat(InputPath, MatlabImpExpCodePath,OutputPath)
% Deal with input variables
if nargin<1
    error('please provide the path to the files containing\nthe snippets and spike arrival time generated by Neuralynx\n');
end
if nargin<2
    if strcmp('BATMAN-PC', getenv('computername'))
        MatlabImpExpCodePath = 'C:\Users\Batman\Documents\Code\MatlabImportExport_v6.0.0';
    else
        MatlabImpExpCodePath = input('Please indicate the path to your MatlabImportExport_v6.0.0 folder','s');
    end
end
if nargin<3
    OutputPath = InputPath;
    fprintf(1, 'No outputpath indicated, data will be saved under the same folder as they were provided:\n%s\n', OutputPath);
else
    fprintf(1, 'Converted files willbe saved under:\n%s\n', OutputPath);
end

% List the files
SU_files = dir(fullfile(InputPath, '*TT*SS*.ntt'));
Num_SU = length(SU_files);

% Setting parameters for Nlx2MatSpike
 FieldSelectionFlags = [1 0 1 0 1];
%     FieldSelectionFlags= Vector with each item being either a zero (excludes
%                        data) or a one (includes data) that determines which
%                        data will be returned for each record. The order of
%                        the items in the vector correspond to the following:
%                           FieldSelectionFlags(1): Timestamps
%                           FieldSelectionFlags(2): Spike Channel Numbers
%                           FieldSelectionFlags(3): Cell Numbers
%                           FieldSelectionFlags(4): Spike Features
%                           FieldSelectionFlags(5): Samples
HeaderExtractionFlag = 1;
%   HeaderExtractionFlag: Either a zero if you do not want to import the header
%                         or a one if header import is desired
ExtractionMode = 1;
%   ExtractionMode: A number indicating how records will be processed during
%                   import. The numbers and their effect are described below:
%                      1 (Extract All): Extracts data from every record in
%                        the file.

% Save the current path we are in
CurrentPath = pwd;

% Go to the MatlabImportExport folder
eval(sprintf('cd %s',MatlabImpExpCodePath));

% Loop through files, extract data
for SU_i=1:Num_SU % for each spike sorted unit
    fprintf(1, 'Converting file %d/%d from ntt to mat\n', SU_i, Num_SU);
    NTT_Filename = fullfile(InputPath, SU_files(SU_i).name);
    Mat_Filename = fullfile(OutputPath,sprintf('%s.mat', SU_files(SU_i).name(1:(end-4))));
   
    [Spike_arrival_times, Spike_sort_ID, Spike_snippets, Header] =...
                     Nlx2MatSpike( NTT_Filename, FieldSelectionFlags,...
                     HeaderExtractionFlag, ExtractionMode,[]); %#ok<ASGLU>
    save(Mat_Filename, 'Spike_arrival_times', 'Spike_sort_ID', 'Spike_snippets', 'Header')
end
% Go back to the initial folder
eval(sprintf('cd %s',CurrentPath));
end